name: Update README with latest YouTube videos

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update YouTube videos in README
        uses: DenverCoder1/github-readme-youtube@v2
        with:
          channel_id: UCKGC8OkNdtaEPihTGh8wuDw   
          max_videos: 5
          readme_path: README.md
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Updated YouTube videos in README'
          git push
